#! /usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 2
bspc config split_ratio 0.5

bspc config focused_border_color "#a6e3a1"
bspc config  normal_border_color "#6c7086"

hsetroot -cover "$HOME/Pictures/Wallpaper"

pgrep -x picom > "/dev/null" || picom &
pgrep -x sxhkd > "/dev/null" || sxhkd &
